# Generated by Django 4.0.6 on 2022-08-30 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_texasapp_rename_texasmedcare_guru'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='guru',
            new_name='contact',
        ),
    ]
