# Generated by Django 4.0.6 on 2023-03-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_rename_guru_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texasapp',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='texasapp',
            name='tp',
        ),
        migrations.AddField(
            model_name='texasapp',
            name='sd',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='Select Doctor', max_length=6),
        ),
    ]
