# Generated by Django 4.0.6 on 2023-03-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_remove_texasapp_dob_remove_texasapp_tp_texasapp_sd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texasapp',
            name='sd',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE')], default='Select Doctor', max_length=6),
        ),
    ]
