# Generated by Django 4.0.6 on 2023-03-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_alter_texasapp_sd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texasapp',
            name='sd',
            field=models.CharField(choices=[('d', 'Select Doctor'), ('d1', 'Andrew'), ('d2', 'Senthil Kumar'), ('d3', 'Afsal'), ('d4', 'Vikram')], default='Select Doctor', max_length=6),
        ),
    ]
