# Generated by Django 4.0.6 on 2023-03-20 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0007_alter_texasapp_sd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='texasapp',
            old_name='box',
            new_name='Health_Issues',
        ),
    ]
