# Generated by Django 4.0.6 on 2023-04-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0008_rename_box_texasapp_health_issues'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME1', models.BooleanField(blank=True, default=False)),
                ('NAME2', models.BooleanField(blank=True, default=False)),
                ('NAME3', models.BooleanField(blank=True, default=False)),
                ('NAME4', models.BooleanField(blank=True, default=False)),
                ('NAME5', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
