# Generated by Django 4.0.6 on 2023-04-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0009_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='NAME1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='NAME2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='NAME3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='NAME4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='NAME5',
            field=models.BooleanField(default=False),
        ),
    ]
