# Generated by Django 4.0.6 on 2023-04-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0010_alter_booking_name1_alter_booking_name2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='NAME1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='NAME2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='NAME3',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='NAME4',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='NAME5',
            field=models.CharField(max_length=10),
        ),
    ]
