# Generated by Django 4.0.6 on 2023-04-13 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0011_alter_booking_name1_alter_booking_name2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='NAME4',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='NAME5',
        ),
    ]
