# Generated by Django 4.0.6 on 2023-04-13 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0012_remove_booking_name4_remove_booking_name5'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Andrew_Booking',
        ),
    ]
