# Generated by Django 4.0.6 on 2023-04-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0013_rename_booking_andrew_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andrew_booking',
            name='NAME1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='andrew_booking',
            name='NAME2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='andrew_booking',
            name='NAME3',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
