# Generated by Django 4.0.6 on 2023-04-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0014_alter_andrew_booking_name1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andrew_booking',
            name='NAME1',
            field=models.CharField(blank=True, default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='andrew_booking',
            name='NAME2',
            field=models.CharField(blank=True, default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='andrew_booking',
            name='NAME3',
            field=models.CharField(blank=True, default=True, max_length=10),
        ),
    ]
