# Generated by Django 4.0.6 on 2023-04-13 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0015_alter_andrew_booking_name1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andrew_booking',
            name='NAME2',
        ),
        migrations.RemoveField(
            model_name='andrew_booking',
            name='NAME3',
        ),
    ]
