# Generated by Django 4.0.6 on 2023-04-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0018_afsalas_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='vikram_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME1', models.CharField(blank=True, default=True, max_length=10)),
            ],
        ),
    ]
